### ISSUE TITLE
Auto detect branch switching

### ISSUE THREAD

**Issue by JottiA** [FPtje/vscode-semaphore-ci#3] opened 2022-06-09 06:17 UTC
Currently when switching active branch, we need to manually refresh the tree by running`semaphore-ci.refreshTree`. It would be great if the extension could detect branch switching and auto refresh the tree.

Also related to https://github.com/FPtje/vscode-semaphore-ci/issues/1

**Comment by FPtje** [comment] 2022-06-30 20:34
This has been released in version `0.1.0`! :tada: 

The tree now refreshes every 5 seconds. If you change branches, you should see a change within about 5 seconds. It is possible to change the refresh delay in the `semaphore-ci` settings if desired.

**Closed as completed by FPtje** 2022-06-30 20:34 UTC

**Comment by FPtje** [comment] 2022-07-01 07:14
Due to some odd quirk, this feature does not work in `0.1.0`. I think the cause for that is that I didn't build before packaging, causing it to package an old version. This should be fixed in `0.1.1`.
